linters:
  # Enable specific linters
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Reports suspicious constructs
    - ineffassign   # Detects unused assignments
    - staticcheck   # Go static analysis
    - typecheck     # Like the front-end of a Go compiler
    - unused        # Checks for unused constants, variables, functions
    - gofmt         # Checks if code was gofmt-ed
    - revive        # Fast, configurable, extensible linter (replaces golint)
    - misspell      # Finds commonly misspelled English words
    - gocyclo       # Checks cyclomatic complexity
    - dupl          # Code clone detection
    - gosec         # Checks for security problems

linters-settings:
  gocyclo:
    # Minimal code complexity to report
    min-complexity: 15
  revive:
    # Minimal confidence for issues
    min-confidence: 0.8

# Maximum issues count per one linter
issues:
  max-issues-per-linter: 0
  max-same-issues: 0

# Output configuration
output:
  # Format: colored-line-number|line-number|json|tab|colored-tab|checkstyle|code-climate|junit-xml|github-actions
  formats:
    - format: colored-line-number