name: Lint and Test

on: pull_request

jobs:
    lint:
        name: Run golangci-lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.24

            - name: Install golangci-lint
              run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

            - name: Run golangci-lint
              run: golangci-lint run

    test:
        name: Run tests with coverage
        runs-on: ubuntu-latest
        needs: lint  # This ensures tests run only if linting passes
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.24

            - name: Run tests
              run: go test -cover ./...
